spring.application.name=javanews

# profile
spring.profiles.active=${APP_PROFILE:test}

# liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# hibernate
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

security.client-id=${CLIENT_ID:myclientid}
security.client-secret=${CLIENT_SECRET:myclientsecret}
security.jwt.duration=${JWT_DURATION:86400}
security.rsa.private-key=classpath:private.pem
security.rsa.public-key=classpath:public.pem
security.rsa.key-id=javanews-rsa-key-v1
cors.origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

spring.mail.host=${EMAIL_HOST:smtp.gmail.com}
spring.mail.port=${EMAIL_PORT:587}
spring.mail.username=${EMAIL_USERNAME:test@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:123456}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

email.password-recover.token.minutes=${PASSWORD_RECOVER_TOKEN_MINUTES:30}
email.password-recover.uri=${PASSWORD_RECOVER_URI:http://localhost:5173/recover-password/}